/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServerIndexRouteImport } from './routes/server.index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as ServerWelcomeRouteImport } from './routes/server.welcome'
import { Route as ServerProgressRouteImport } from './routes/server.progress'
import { Route as ServerMenuRouteImport } from './routes/server.menu'
import { Route as ManagerTeamRouteImport } from './routes/manager.team'
import { Route as ManagerPrioritiesRouteImport } from './routes/manager.priorities'
import { Route as ManagerMenuRouteImport } from './routes/manager.menu'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as DemoServerIndexRouteImport } from './routes/demo.server.index'
import { Route as DemoManagerIndexRouteImport } from './routes/demo.manager.index'
import { Route as ManagerServerIdRouteImport } from './routes/manager.server.$id'
import { Route as DemoServerWelcomeRouteImport } from './routes/demo.server.welcome'
import { Route as DemoServerProgressRouteImport } from './routes/demo.server.progress'
import { Route as DemoServerMenuRouteImport } from './routes/demo.server.menu'
import { Route as DemoManagerTeamRouteImport } from './routes/demo.manager.team'
import { Route as DemoManagerPrioritiesRouteImport } from './routes/demo.manager.priorities'
import { Route as DemoManagerMenuRouteImport } from './routes/demo.manager.menu'
import { Route as DemoManagerServerIdRouteImport } from './routes/demo.manager.server.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerIndexRoute = ServerIndexRouteImport.update({
  id: '/server/',
  path: '/server/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerWelcomeRoute = ServerWelcomeRouteImport.update({
  id: '/server/welcome',
  path: '/server/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerProgressRoute = ServerProgressRouteImport.update({
  id: '/server/progress',
  path: '/server/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerMenuRoute = ServerMenuRouteImport.update({
  id: '/server/menu',
  path: '/server/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerTeamRoute = ManagerTeamRouteImport.update({
  id: '/manager/team',
  path: '/manager/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerPrioritiesRoute = ManagerPrioritiesRouteImport.update({
  id: '/manager/priorities',
  path: '/manager/priorities',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerMenuRoute = ManagerMenuRouteImport.update({
  id: '/manager/menu',
  path: '/manager/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoServerIndexRoute = DemoServerIndexRouteImport.update({
  id: '/server/',
  path: '/server/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoManagerIndexRoute = DemoManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => DemoRoute,
} as any)
const ManagerServerIdRoute = ManagerServerIdRouteImport.update({
  id: '/manager/server/$id',
  path: '/manager/server/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoServerWelcomeRoute = DemoServerWelcomeRouteImport.update({
  id: '/server/welcome',
  path: '/server/welcome',
  getParentRoute: () => DemoRoute,
} as any)
const DemoServerProgressRoute = DemoServerProgressRouteImport.update({
  id: '/server/progress',
  path: '/server/progress',
  getParentRoute: () => DemoRoute,
} as any)
const DemoServerMenuRoute = DemoServerMenuRouteImport.update({
  id: '/server/menu',
  path: '/server/menu',
  getParentRoute: () => DemoRoute,
} as any)
const DemoManagerTeamRoute = DemoManagerTeamRouteImport.update({
  id: '/manager/team',
  path: '/manager/team',
  getParentRoute: () => DemoRoute,
} as any)
const DemoManagerPrioritiesRoute = DemoManagerPrioritiesRouteImport.update({
  id: '/manager/priorities',
  path: '/manager/priorities',
  getParentRoute: () => DemoRoute,
} as any)
const DemoManagerMenuRoute = DemoManagerMenuRouteImport.update({
  id: '/manager/menu',
  path: '/manager/menu',
  getParentRoute: () => DemoRoute,
} as any)
const DemoManagerServerIdRoute = DemoManagerServerIdRouteImport.update({
  id: '/manager/server/$id',
  path: '/manager/server/$id',
  getParentRoute: () => DemoRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/manager/menu': typeof ManagerMenuRoute
  '/manager/priorities': typeof ManagerPrioritiesRoute
  '/manager/team': typeof ManagerTeamRoute
  '/server/menu': typeof ServerMenuRoute
  '/server/progress': typeof ServerProgressRoute
  '/server/welcome': typeof ServerWelcomeRoute
  '/manager/': typeof ManagerIndexRoute
  '/server/': typeof ServerIndexRoute
  '/demo/manager/menu': typeof DemoManagerMenuRoute
  '/demo/manager/priorities': typeof DemoManagerPrioritiesRoute
  '/demo/manager/team': typeof DemoManagerTeamRoute
  '/demo/server/menu': typeof DemoServerMenuRoute
  '/demo/server/progress': typeof DemoServerProgressRoute
  '/demo/server/welcome': typeof DemoServerWelcomeRoute
  '/manager/server/$id': typeof ManagerServerIdRoute
  '/demo/manager/': typeof DemoManagerIndexRoute
  '/demo/server/': typeof DemoServerIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/demo/manager/server/$id': typeof DemoManagerServerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/manager/menu': typeof ManagerMenuRoute
  '/manager/priorities': typeof ManagerPrioritiesRoute
  '/manager/team': typeof ManagerTeamRoute
  '/server/menu': typeof ServerMenuRoute
  '/server/progress': typeof ServerProgressRoute
  '/server/welcome': typeof ServerWelcomeRoute
  '/manager': typeof ManagerIndexRoute
  '/server': typeof ServerIndexRoute
  '/demo/manager/menu': typeof DemoManagerMenuRoute
  '/demo/manager/priorities': typeof DemoManagerPrioritiesRoute
  '/demo/manager/team': typeof DemoManagerTeamRoute
  '/demo/server/menu': typeof DemoServerMenuRoute
  '/demo/server/progress': typeof DemoServerProgressRoute
  '/demo/server/welcome': typeof DemoServerWelcomeRoute
  '/manager/server/$id': typeof ManagerServerIdRoute
  '/demo/manager': typeof DemoManagerIndexRoute
  '/demo/server': typeof DemoServerIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/demo/manager/server/$id': typeof DemoManagerServerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/manager/menu': typeof ManagerMenuRoute
  '/manager/priorities': typeof ManagerPrioritiesRoute
  '/manager/team': typeof ManagerTeamRoute
  '/server/menu': typeof ServerMenuRoute
  '/server/progress': typeof ServerProgressRoute
  '/server/welcome': typeof ServerWelcomeRoute
  '/manager/': typeof ManagerIndexRoute
  '/server/': typeof ServerIndexRoute
  '/demo/manager/menu': typeof DemoManagerMenuRoute
  '/demo/manager/priorities': typeof DemoManagerPrioritiesRoute
  '/demo/manager/team': typeof DemoManagerTeamRoute
  '/demo/server/menu': typeof DemoServerMenuRoute
  '/demo/server/progress': typeof DemoServerProgressRoute
  '/demo/server/welcome': typeof DemoServerWelcomeRoute
  '/manager/server/$id': typeof ManagerServerIdRoute
  '/demo/manager/': typeof DemoManagerIndexRoute
  '/demo/server/': typeof DemoServerIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/demo/manager/server/$id': typeof DemoManagerServerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/settings'
    | '/checkout/success'
    | '/manager/menu'
    | '/manager/priorities'
    | '/manager/team'
    | '/server/menu'
    | '/server/progress'
    | '/server/welcome'
    | '/manager/'
    | '/server/'
    | '/demo/manager/menu'
    | '/demo/manager/priorities'
    | '/demo/manager/team'
    | '/demo/server/menu'
    | '/demo/server/progress'
    | '/demo/server/welcome'
    | '/manager/server/$id'
    | '/demo/manager/'
    | '/demo/server/'
    | '/api/public/payments/webhook'
    | '/demo/manager/server/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/settings'
    | '/checkout/success'
    | '/manager/menu'
    | '/manager/priorities'
    | '/manager/team'
    | '/server/menu'
    | '/server/progress'
    | '/server/welcome'
    | '/manager'
    | '/server'
    | '/demo/manager/menu'
    | '/demo/manager/priorities'
    | '/demo/manager/team'
    | '/demo/server/menu'
    | '/demo/server/progress'
    | '/demo/server/welcome'
    | '/manager/server/$id'
    | '/demo/manager'
    | '/demo/server'
    | '/api/public/payments/webhook'
    | '/demo/manager/server/$id'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/login'
    | '/settings'
    | '/checkout/success'
    | '/manager/menu'
    | '/manager/priorities'
    | '/manager/team'
    | '/server/menu'
    | '/server/progress'
    | '/server/welcome'
    | '/manager/'
    | '/server/'
    | '/demo/manager/menu'
    | '/demo/manager/priorities'
    | '/demo/manager/team'
    | '/demo/server/menu'
    | '/demo/server/progress'
    | '/demo/server/welcome'
    | '/manager/server/$id'
    | '/demo/manager/'
    | '/demo/server/'
    | '/api/public/payments/webhook'
    | '/demo/manager/server/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ManagerMenuRoute: typeof ManagerMenuRoute
  ManagerPrioritiesRoute: typeof ManagerPrioritiesRoute
  ManagerTeamRoute: typeof ManagerTeamRoute
  ServerMenuRoute: typeof ServerMenuRoute
  ServerProgressRoute: typeof ServerProgressRoute
  ServerWelcomeRoute: typeof ServerWelcomeRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
  ServerIndexRoute: typeof ServerIndexRoute
  ManagerServerIdRoute: typeof ManagerServerIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/': {
      id: '/server/'
      path: '/server'
      fullPath: '/server/'
      preLoaderRoute: typeof ServerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/welcome': {
      id: '/server/welcome'
      path: '/server/welcome'
      fullPath: '/server/welcome'
      preLoaderRoute: typeof ServerWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/progress': {
      id: '/server/progress'
      path: '/server/progress'
      fullPath: '/server/progress'
      preLoaderRoute: typeof ServerProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/menu': {
      id: '/server/menu'
      path: '/server/menu'
      fullPath: '/server/menu'
      preLoaderRoute: typeof ServerMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/team': {
      id: '/manager/team'
      path: '/manager/team'
      fullPath: '/manager/team'
      preLoaderRoute: typeof ManagerTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/priorities': {
      id: '/manager/priorities'
      path: '/manager/priorities'
      fullPath: '/manager/priorities'
      preLoaderRoute: typeof ManagerPrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/menu': {
      id: '/manager/menu'
      path: '/manager/menu'
      fullPath: '/manager/menu'
      preLoaderRoute: typeof ManagerMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/server/': {
      id: '/demo/server/'
      path: '/server'
      fullPath: '/demo/server/'
      preLoaderRoute: typeof DemoServerIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/manager/': {
      id: '/demo/manager/'
      path: '/manager'
      fullPath: '/demo/manager/'
      preLoaderRoute: typeof DemoManagerIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/manager/server/$id': {
      id: '/manager/server/$id'
      path: '/manager/server/$id'
      fullPath: '/manager/server/$id'
      preLoaderRoute: typeof ManagerServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/server/welcome': {
      id: '/demo/server/welcome'
      path: '/server/welcome'
      fullPath: '/demo/server/welcome'
      preLoaderRoute: typeof DemoServerWelcomeRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/server/progress': {
      id: '/demo/server/progress'
      path: '/server/progress'
      fullPath: '/demo/server/progress'
      preLoaderRoute: typeof DemoServerProgressRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/server/menu': {
      id: '/demo/server/menu'
      path: '/server/menu'
      fullPath: '/demo/server/menu'
      preLoaderRoute: typeof DemoServerMenuRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/manager/team': {
      id: '/demo/manager/team'
      path: '/manager/team'
      fullPath: '/demo/manager/team'
      preLoaderRoute: typeof DemoManagerTeamRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/manager/priorities': {
      id: '/demo/manager/priorities'
      path: '/manager/priorities'
      fullPath: '/demo/manager/priorities'
      preLoaderRoute: typeof DemoManagerPrioritiesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/manager/menu': {
      id: '/demo/manager/menu'
      path: '/manager/menu'
      fullPath: '/demo/manager/menu'
      preLoaderRoute: typeof DemoManagerMenuRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/manager/server/$id': {
      id: '/demo/manager/server/$id'
      path: '/manager/server/$id'
      fullPath: '/demo/manager/server/$id'
      preLoaderRoute: typeof DemoManagerServerIdRouteImport
      parentRoute: typeof DemoRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DemoRouteChildren {
  DemoManagerMenuRoute: typeof DemoManagerMenuRoute
  DemoManagerPrioritiesRoute: typeof DemoManagerPrioritiesRoute
  DemoManagerTeamRoute: typeof DemoManagerTeamRoute
  DemoServerMenuRoute: typeof DemoServerMenuRoute
  DemoServerProgressRoute: typeof DemoServerProgressRoute
  DemoServerWelcomeRoute: typeof DemoServerWelcomeRoute
  DemoManagerIndexRoute: typeof DemoManagerIndexRoute
  DemoServerIndexRoute: typeof DemoServerIndexRoute
  DemoManagerServerIdRoute: typeof DemoManagerServerIdRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoManagerMenuRoute: DemoManagerMenuRoute,
  DemoManagerPrioritiesRoute: DemoManagerPrioritiesRoute,
  DemoManagerTeamRoute: DemoManagerTeamRoute,
  DemoServerMenuRoute: DemoServerMenuRoute,
  DemoServerProgressRoute: DemoServerProgressRoute,
  DemoServerWelcomeRoute: DemoServerWelcomeRoute,
  DemoManagerIndexRoute: DemoManagerIndexRoute,
  DemoServerIndexRoute: DemoServerIndexRoute,
  DemoManagerServerIdRoute: DemoManagerServerIdRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ManagerMenuRoute: ManagerMenuRoute,
  ManagerPrioritiesRoute: ManagerPrioritiesRoute,
  ManagerTeamRoute: ManagerTeamRoute,
  ServerMenuRoute: ServerMenuRoute,
  ServerProgressRoute: ServerProgressRoute,
  ServerWelcomeRoute: ServerWelcomeRoute,
  ManagerIndexRoute: ManagerIndexRoute,
  ServerIndexRoute: ServerIndexRoute,
  ManagerServerIdRoute: ManagerServerIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
